version: 1
global:
  api:
    provider: dongchuangai
    baseUrl: https://api.dongchuangai.com/v1
    apiKey: sk-f44ddd933d221b13d4d5c48362b778bb8694cac4452bf939
    model: gpt-5.5
    authSource: dongchuangai-oauth
    authAccountName: 李春锃
    authAccountPhone: ""
  launch:
    openclawConfigPath: D:\myworks\便携式u盘\.openclaw\state\openclaw.json
    openclawStateDir: D:\myworks\便携式u盘\.openclaw\state
    webUrls:
      openclaw: http://127.0.0.1:18789
      hermes: ""
      claude: http://127.0.0.1:8081
      codex: http://127.0.0.1:8082
      deepseek-harness: http://127.0.0.1:3080
    persistSystemPath: true
  update:
    app_id: 30
    user_id: 50
apps:
  openclaw:
    wechat:
      enabled: true
      accountId: b8223f12f106-im-bot
      token: b8223f12f106@im.bot:06000094977c7574f9d7be3e54e4f7df92f7b4
      baseUrl: https://ilinkai.weixin.qq.com
      cdnBaseUrl: https://novac2c.cdn.weixin.qq.com/c2c
      dmPolicy: open
      groupPolicy: disabled
      allowFrom: []
      groupAllowFrom: []
      splitMultilineMessages: false
  hermes:
    wechat:
      enabled: false
      accountId: ""
      token: ""
      baseUrl: https://ilinkai.weixin.qq.com
      cdnBaseUrl: https://novac2c.cdn.weixin.qq.com/c2c
      dmPolicy: open
      groupPolicy: disabled
      allowFrom: []
      groupAllowFrom: []
      splitMultilineMessages: false
  claude:
    wechat:
      enabled: false
      accountId: ""
      token: ""
      baseUrl: https://ilinkai.weixin.qq.com
      cdnBaseUrl: https://novac2c.cdn.weixin.qq.com/c2c
      dmPolicy: open
      groupPolicy: disabled
      allowFrom: []
      groupAllowFrom: []
      splitMultilineMessages: false
  codex:
    wechat:
      enabled: false
      accountId: ""
      token: ""
      baseUrl: https://ilinkai.weixin.qq.com
      cdnBaseUrl: https://novac2c.cdn.weixin.qq.com/c2c
      dmPolicy: open
      groupPolicy: disabled
      allowFrom: []
      groupAllowFrom: []
      splitMultilineMessages: false
  deepseek-harness:
    wechat:
      enabled: false
      accountId: ""
      token: ""
      baseUrl: https://ilinkai.weixin.qq.com
      cdnBaseUrl: https://novac2c.cdn.weixin.qq.com/c2c
      dmPolicy: open
      groupPolicy: disabled
      allowFrom: []
      groupAllowFrom: []
      splitMultilineMessages: false
